// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqSQNm7Q_eP_cZC-e5rq2KCjIVrFepjhc',
    appId: '1:68095816941:web:e53b126c3c2abcdaaa08e4',
    messagingSenderId: '68095816941',
    projectId: 'essu-alumni-tracker-9ded3',
    authDomain: 'essu-alumni-tracker-9ded3.firebaseapp.com',
    storageBucket: 'essu-alumni-tracker-9ded3.firebasestorage.app',
    measurementId: 'G-BK6JNH0D91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJX0wBrEm7m262m2pIucQu4cv1LMLNhE4',
    appId: '1:68095816941:android:519765fafff53893aa08e4',
    messagingSenderId: '68095816941',
    projectId: 'essu-alumni-tracker-9ded3',
    storageBucket: 'essu-alumni-tracker-9ded3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJlAcY4xLgUQo8JvQ9zKjxNIkDak0MUeY',
    appId: '1:68095816941:ios:8f934e13145294faaa08e4',
    messagingSenderId: '68095816941',
    projectId: 'essu-alumni-tracker-9ded3',
    storageBucket: 'essu-alumni-tracker-9ded3.firebasestorage.app',
    iosBundleId: 'com.example.essuAlumniTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJlAcY4xLgUQo8JvQ9zKjxNIkDak0MUeY',
    appId: '1:68095816941:ios:8f934e13145294faaa08e4',
    messagingSenderId: '68095816941',
    projectId: 'essu-alumni-tracker-9ded3',
    storageBucket: 'essu-alumni-tracker-9ded3.firebasestorage.app',
    iosBundleId: 'com.example.essuAlumniTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqSQNm7Q_eP_cZC-e5rq2KCjIVrFepjhc',
    appId: '1:68095816941:web:01865d1b223e307baa08e4',
    messagingSenderId: '68095816941',
    projectId: 'essu-alumni-tracker-9ded3',
    authDomain: 'essu-alumni-tracker-9ded3.firebaseapp.com',
    storageBucket: 'essu-alumni-tracker-9ded3.firebasestorage.app',
    measurementId: 'G-BVLGHDL0EY',
  );

}